As we do not have animationMode implemented do not set the instance
When this function was called it crashed of corse like this:
[Skin] Processing screen 'NumericalTextInputHelpDialog', position=(537, 675), size=(846 x 246) for module 'NumericalTextInputHelpDialog'.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 92, in selectionChanged
    self.current[1].onSelect(self.session)
  File "/usr/lib/enigma2/python/Components/config.py", line 1442, in onSelect
    self.help_window.setAnimationMode(0)
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 206, in setAnimationMode
    self.instance.setAnimationMode(mode)
AttributeError: 'eWindow' object has no attribute 'setAnimationMode'
[ePyObject] (CallObject(<bound method ConfigList.selectionChanged of <Components.ConfigList.ConfigList object at 0xad3c6af0>>,()) failed)
[gRC] Warning: Main thread is busy, displaying spinner!
Killed