small updates (#3484)
-disable power on/off when not active any day
-check infobar instance
-sleeptimer iptv service use as dvb service
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3585, in
setSleepTimer
OverflowError: Python int too large to convert to C long