[StartEnigma] Add missing funtion <  9688.587> 2026-06-14 12:03:18+0300 [-]   File /usr/lib/enigma2/python/StartEnigma.py, line 476, in doAction <  9688.588> 2026-06-14 12:03:18+0300 [-]     menu_screen = self.session.openWithCallback(self.MenuClosed, MainMenu, x) <  9688.588> 2026-06-14 12:03:18+0300 [-]                                                 ^^^^^^^^^^^^^^^ <  9688.588> 2026-06-14 12:03:18+0300 [-] AttributeError: 'PowerKey' object has no attribute 'MenuClosed'