[PluginBrowser] Fix crash 2024-05-31 20:53:49+0300 [-]   File /usr/lib/enigma2/python/StartEnigma.py, line 255, in processDelay 2024-05-31 20:53:49+0300 [-]     callback(*retval) 2024-05-31 20:53:49+0300 [-] TypeError: PluginBrowserNew.PluginDownloadBrowserClosed() missing 1 required positional argument: 'returnValue'