[ImportChannels] Resolve crash in ImportChannels when a remote box could not be reached [Import Channels] URLError  <urlopen error [Errno 111] Connection refused> Exception in thread ChannelsImport: Traceback (most recent call last):   File /usr/lib/python3.9/threading.py, line 973, in _bootstrap_inner   File /usr/lib/python3.9/threading.py, line 910, in run   File /usr/lib/enigma2/python/Components/ImportChannels.py, line 125, in threaded_function     settings = self.getFallbackSettings()   File /usr/lib/enigma2/python/Components/ImportChannels.py, line 60, in getFallbackSettings     result = self.getUrl(%s/api/settings % self.getTerrestrialUrl()).read() AttributeError: 'dict' object has no attribute 'read'
TODO: when we have a different URL for the terristical fallback tuner the
settings are only taken from this terristical server. Also the EPG. This
needs to be resolved as well

cherry-pick > https://github.com/OpenPLi/enigma2/commit/6834f1ec2d545493041679cd1be7ae3b91d1ebb5