"[ChannelSelection]" fix crash :
TypeError: ChannelSelection.bouquetParentalControlCallback() got an unexpected keyword argument 'forceRestart'

Because of this commit -> https://github.com/openatv/enigma2/commit/408d54814a48b6895f25318951a2aa6cdf597a4a