FallbackTimer.py: Encode instead of decode
Fix add and edit timer with fallbacktuner.

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/StartEnigma.py", line 223, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Screens/EventView.py", line 176, in finishedAdd
  File "/usr/lib/enigma2/python/Tools/FallbackTimer.py", line 103, in addTimer
    quote(timer.name.decode('utf8').encode('utf8', 'ignore')),
AttributeError: 'str' object has no attribute 'decode'