Resolve possible GSOD when opening MainMenu.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1091, in mainMenu
  File "/usr/lib/enigma2/python/StartEnigma.py", line 296, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 306, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 249, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 273, in doInstantiateDialog
    dlg.applySkin()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 263, in applySkin
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 296, in createGUIScreen
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 251, in layoutFinished
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 239, in screenContentChanged
  File "skin applet", line 21, in <module>
AttributeError: 'MainMenu' object has no attribute 'setFont'
[ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xaf7acaa8>>,('InfobarMenuActions', 'mainMenu')) failed)

Introduced in commit
https://github.com/OpenPLi/enigma2/commit/e960a135bdf0540d11b34ff25af13887eabee2b9.
I'm not fully shure if this was somehow intended