try/except show ci message screen
File "/usr/lib/enigma2/python/Screens/Ci.py", line 350, in
ciStateChanged
  File "/usr/lib/enigma2/python/StartEnigma.py", line
302, in openWithCallback
    dlg = self.open(screen, *arguments,
**kwargs)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 308, in
open
    raise RuntimeError("modal open are allowed only from a screen
which is modal!")
RuntimeError: modal open are allowed only from a
screen which is modal!