Solve possible GSOD due to forgotten sort during py2 to 3 transferSolve a forgotten sort
Observed during trying to solve the autoinstall/autorestore feature

[(20, <function VideoWizard at 0xb1d675c8>), (0, <class 'Screens.StartWizard.AutoInstallWizard'>), (0, <class 'Screens.StartWizard.AutoRestoreWizard'>), (10, <class 'Screens.LanguageSelection.LanguageWizard'>), (30, <class 'Plugins.SystemPlugins.OSDPositionSetup.overscanwizard.OverscanWizard'>), (40, <class 'Screens.StartWizard.StartWizard'>), (100, <class 'Screens.InfoBar.InfoBar'>)]

[StartEnigma] EXCEPTION IN PYTHON STARTUP CODE:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/StartEnigma.py", line 613, in <module>
    runScreenTest()
  File "/usr/lib/enigma2/python/StartEnigma.py", line 471, in runScreenTest
    screensToRun.sort()
TypeError: '<' not supported between instances of 'type' and 'type'
-----------------------------------------------------------